# Generated by Django 2.1.2 on 2018-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carbs',
            field=models.IntegerField(default=206),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat',
            field=models.IntegerField(default=67),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein',
            field=models.IntegerField(default=146),
        ),
    ]
