# Generated by Django 2.1.2 on 2018-11-06 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20181106_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='fooditems',
        ),
        migrations.RemoveField(
            model_name='foodplan',
            name='protein',
        ),
        migrations.AddField(
            model_name='foodplan',
            name='food_plan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
