# Generated by Django 2.1.2 on 2018-11-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_foodplan_test_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplan',
            name='food_plan',
        ),
        migrations.AddField(
            model_name='foodplan',
            name='plan_items',
            field=models.ManyToManyField(to='planner.FoodItem'),
        ),
    ]
